ami_value = "ami-0e449927258d45bc4"
instance_type = "t2.micro"
key_value = "Vijay-Test-Key-pair"
s3bucket_name = "my-new-bucket-for-terraform5543"
instanceName_value = "vijayinstance"
instanceclienttag_value = "IND"